name: deploy

on:
  push:
    branches: [main]

jobs:
  files:
    name: Prepare gas files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/gas-cli:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Untar Garfield gas files
        run: |
          cd public/gas/garfield
          for i in *.gas.tar.gz; do tar -xzvf $i; done
          rm *.gas.tar.gz

      - name: generate gas json files
        run: |
          cd public/gas/garfield
          for i in *.gas; do gas-cli read -i $i --dir ../json --json; done

      - name: test files
        run: |
          ls -lht public/gas/garfield
          ls -lht public/gas/json

      - name: Cache gas files
        uses: actions/cache@v3
        id: gas-files
        with:
          key: gas-files-${{ github.sha }}
          path: public

      - name: test files
        run: |
          ls -lht public/gas/garfield
          ls -lht public/gas/json

  build:
    name: Build React App
    runs-on: ubuntu-latest
    needs: files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: test files
        run: |
          ls -lht public/gas/garfield
          ls -lht public/gas/json

      - name: Restore cache
        uses: actions/cache@v3
        id: gas-files
        with:
          key: gas-files-${{ github.sha }}
          path: public

      - name: test files
        run: |
          ls -lht public/gas/garfield
          ls -lht public/gas/json

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Build
        run: |
          export PUBLIC_URL=https://lobis.github.io/gas-graphs/
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy: # https://github.com/actions/deploy-pages
    name: GitHub Pages deployment
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
